# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptscan',
            name='text',
        ),
        migrations.AddField(
            model_name='receiptscan',
            name='raw',
            field=models.TextField(default=''),
        ),
    ]
