# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_receiptscan_as_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptscan',
            name='as_lines',
        ),
    ]
